      outfile = out                    * recording the running information
      intxtfile = reads.txt            * txt file generated by bismark
      outreadfile = sel_reads          * the index of reads file in which the reads include assigned methylated site
      flag = p                         * p means paired-ends; s means singled-end
      skipped_number = 1               * the number of the rows which will be skipped
      inmultxtfile = reads_mul.txt     * mul.txt file generated by bismark
      
     