      outfile = out               * recording the running information
      gtffile = transcripts.gtf   * gtf file generated by cufflinks
      fafile  = genome.fa         * genome file
      transfile = out_trans       * recording the transcript
      seqfile = out_seq.fa        * recording the DNA sequence of each trascript
      seqlength = 50              * the length of sequence in the seqfile
      
     