/* trans2genom.c

   Junfeng Liu, 2016
   
   This is an program to convert the position of transcriptome to the position of genome according to the file generated by bismark_methylation_extractor and out_trans.

   gcc -o trans2genom-bismark trans2genom-bismark.c -lm
   
   trans2genom-bismark <pe.txt generated by bismark_methylation_extractor > <out_trans>

*/

#include<stdio.h>
#include<string.h>
#include<errno.h>
#include<stdlib.h>
#include<math.h>

/*The function is used to convert the position of transcriptome to the position of genome according to the file pe.txt and out_trans*/
int convert (char *summary_complex, char *out_trans);
/*The function is used to compute the position in genome according the assigned transcriptom position*/
int pos_ge (char *trans_name, char *pos, char *out_trans);

/*The function is used to test transname*/
int pos_test (char *trans_name, char *ls);

/*Global variable for genome postion*/
char pos_genom[1000];

int main (int argc, char* argv[])
{
	 int l;
   
   char out_trans[1000], summary_complex[1000];

   if(argc>2) {
   	strcpy(summary_complex, argv[1]);
   	strcpy(out_trans, argv[2]);
   } else {
   	return -1;
   }

   l=convert(summary_complex,out_trans);
     
   return (l);
}

int convert (char *summary_complex, char *out_trans)
{
	/* j for chracter loop about each row of the methylation_summary-complex file;
     read for column loop about each row;
     k for character loop about each column;
     l for 'for loop';
  */
	int k, j, l, read;
	
	/* j1 for chracter loop about the fourth column of the methylation_summary-complex file;
     read1 for segment loop about the fourth column of the methylation_summary-complex file;
     k1 for character loop about each segment;
  */
	int k1, j1, read1;
	
	/*ls[] for each row of the methylation_summary-complex file;
	  temp[] for each column of the row;
	  ls1[] for each row of the out_trans file;
	*/
	char ls[5000], ls1[5000], temp[1000];
	
  /*trans_name[] is for the transcript name;
    pre_trans_name[] is for the previous transcript name;
  */
  char trans_name[1000], pre_trans_name[1000];
	
	FILE *fcomplex, *fout, *foutls, *ftrans;
	
	if((fcomplex=fopen(summary_complex, "r"))==NULL) {
		return -1;
  }
     
	if((fout=fopen("methylation_genom", "w"))==NULL) {
   	return -1;
  }
  
  if((ftrans=fopen(out_trans, "r"))==NULL) {
		return -1;
  }
    
  
  /*pre_trans_name[] initial value*/
  strcpy(pre_trans_name,"pretransname");
  
  
  /*read each row of the methylation_summary-complex file*/
	while(fgets(ls,5000,fcomplex) != NULL) {
		k=0;
	 	j=0;
	 	read=0;
	 	memset(temp,0,sizeof(temp));
	 	memset(trans_name,0,sizeof(trans_name));
	 	while(read<5) {
	 		temp[k]=ls[j];
	 		if(ls[j]==' '||ls[j]=='\t'||ls[j]=='\n') {
	 			if(read==0) {
	 				fprintf(fout,"%s",temp);
	 			}
	 			if(read==1) {
	 				fprintf(fout,"%s",temp);
	 			}
	 			if(read==2) {
	 				for(l=0;l<k;l++) {
	 					trans_name[l]=temp[l];
	 				}
	 				fprintf(fout,"%s\t",trans_name);
	 				if(strncmp(temp,pre_trans_name,k)!=0) {
	 					if(strcmp(pre_trans_name,"pretransname")==0) {
	 						for(l=0;l<2;l++) {
	 							if(fgets(ls1,5000,ftrans) == NULL) {
	 								rewind(ftrans);
	 								break;
	 							}
	 							l=pos_test(trans_name,ls1);
	 						}
	 						if((foutls=fopen("out_trans_temp", "w"))==NULL) {
	 							return -1;
	 						}
	 						fprintf(foutls,"%s",ls1);
	 						fclose(foutls);
	 						memset(pre_trans_name,0,sizeof(pre_trans_name));
	 						for(l=0;l<k;l++) {
	 							pre_trans_name[l]=temp[l];
	 						}
	 					} else {
	 						for(l=0;l<2;l++) {
	 							if(fgets(ls1,5000,ftrans) == NULL) {
	 								rewind(ftrans);
	 								break;
	 							}
	 							l=pos_test(trans_name,ls1);
	 						}
	 						if((foutls=fopen("out_trans_temp", "w"))==NULL) {
	 							return -1;
	 						}
	 						fprintf(foutls,"%s",ls1);
	 						fclose(foutls);
	 						memset(pre_trans_name,0,sizeof(pre_trans_name));
	 						for(l=0;l<k;l++) {
	 							pre_trans_name[l]=temp[l];
	 						}
	 					}
	 				}
	 			}
	 			if(read==3) {
	 				memset(pos_genom,0,sizeof(pos_genom));
	 				pos_ge(trans_name,temp,"out_trans_temp");
	 				fprintf(fout,"%s\t",pos_genom);
	 			}
	 			if(read==4) {
	 				fprintf(fout,"%s",temp);
	 			}
	 			memset(temp,0,sizeof(temp));
	 			read=read+1;
	 			k=0;
	 		} else {
	 			k=k+1;
	 		}
	 		j=j+1;
	 	}
	}
	fclose(fcomplex);
	fclose(fout);
	fclose(ftrans);
	return 0;
}

int pos_ge(char *trans_name, char *pos, char *out_trans) {
	
	
	/* j for chracter loop about each row of the hits file;
     read for column loop about each row;
     k for character loop about each column;
     l for 'for loop';
  */
	int k, j, l, read;
	
	long n1, n2, n3, n4;
	
	
	/*ls[] for each row of the hits file;
	  temp[] for each column of the row;
	*/
	char ls[5000], temp[1000], temp2[1000], temp3[1000], pos_ls[1000];
	
	
	FILE *fout_trans;
	
	if((fout_trans=fopen(out_trans, "r"))==NULL) {
   	return -1;
  }
  
  memset(pos_ls,0,sizeof(pos_ls));
  
  for(l=0;l<strlen(pos)-1;l++) {
  	pos_ls[l]=pos[l];
  }
   
  n4=0;
  
  while(fgets(ls,5000,fout_trans) != NULL) {
  	k=0;
	 	j=0;
	 	read=0;
	 	n1=0;
	 	n2=0;
	 	n3=0;
	 	memset(temp,0,sizeof(temp));
   	memset(temp2,0,sizeof(temp2));
   	memset(temp3,0,sizeof(temp3));
   	while(read<1000) {
   		temp[k]=ls[j];
	 		if(ls[j]==' '||ls[j]=='\t'||ls[j]=='\n') {
	 			if(read==0) {
	 				for(l=0;l<k;l++) {
	 					temp2[l]=temp[l];
	 				}
	 			}
	 			if(read==1) {
	 				if(strncmp(temp,trans_name,strlen(trans_name))!=0) {
	 					break;
	 				}
	 			}
	 			if((read>=2)&&(fmod(read,2)==0)) {
	 				n1=atol(temp);
	 			}
	 			if((read>=2)&&(fmod(read,2)==1)) {
	 				n2=atol(temp);
	 			}
	 			if((n2>=n1)&&(n1>0)) {
	 				n3=n3+(n2-n1)+1;
	 				if(atol(pos_ls)<=n3) {
	 					n4=n2-(n3-atol(pos_ls));
	 					sprintf(temp3,"%ld",n4);
	 					strcat(pos_genom,temp2);
	 					strcat(pos_genom,"-");
	 					strcat(pos_genom,temp3);
	 					break;
	 				}
	 			}
	 			memset(temp,0,sizeof(temp));
	 			read=read+1;
	 			k=0;
	 		} else {
	 			k=k+1;
	 		}
	 		j=j+1;
   	}
   	if(n4>0) {
   		break;
   	}
  }
  fclose(fout_trans);
  return 0; 
}

int pos_test(char *trans_name, char *ls) {
	
	
	/* j for chracter loop about each row of the hits file;
     read for column loop about each row;
     k for character loop about each column;
     l for 'for loop';
  */
	int k, j, l, read;
	
	int n;
	
	/*
	  temp[] for each column of the row;
	*/
	char temp[1000];
	

  	k=0;
	 	j=0;
	 	read=0;
	 	memset(temp,0,sizeof(temp));
   	while(read<2) {
   		temp[k]=ls[j];
	 		if(ls[j]==' '||ls[j]=='\t'||ls[j]=='\n') {
	 			if(read==1) {
	 				if(strncmp(temp,trans_name,strlen(trans_name))==0) {
	 					n=2;
	 				} else {
	 					n=0;
	 				}
	 			}
	 			memset(temp,0,sizeof(temp));
	 			read=read+1;
	 			k=0;
	 		} else {
	 			k=k+1;
	 		}
	 		j=j+1;
   	}
   	
 
  return n; 
}